spring:
  application:
    name: envelope
  profiles:
    active: ${ENV:dev}
  datasource:
    database: ${DB_DATABASE}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-root.yml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  error:
    include-message: always